# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/stocksurfer',
                'doc_host': 'https://ankurdivekar.github.io',
                'git_url': 'https://github.com/ankurdivekar/stocksurfer',
                'lib_path': 'stocksurfer'},
  'syms': { 'stocksurfer.stockdata': { 'stocksurfer.stockdata.foo': ('stockdata.html#foo', 'stocksurfer/stockdata.py'),
                                       'stocksurfer.stockdata.say_hello': ('stockdata.html#say_hello', 'stocksurfer/stockdata.py')},
            'stocksurfer.strategies': {'stocksurfer.strategies.foobar': ('strategies.html#foobar', 'stocksurfer/strategies.py')}}}
