# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/stocksurfer',
                'doc_host': 'https://ankurdivekar.github.io',
                'git_url': 'https://github.com/ankurdivekar/stocksurfer',
                'lib_path': 'stocksurfer'},
  'syms': {'stocksurfer.core': {'stocksurfer.core.foo': ('core.html#foo', 'stocksurfer/core.py')}}}
