# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_databases.ipynb.

# %% auto 0
__all__ = ['base_path']

# %% ../nbs/03_databases.ipynb 2
import nbdev
import duckdb

# %% ../nbs/03_databases.ipynb 3
base_path = nbdev.config.get_config().lib_path
