# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_stockdata.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_stockdata.ipynb 2
def say_hello(to:str):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_stockdata.ipynb 10
def foo(): pass
