# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_strategies.ipynb.

# %% auto 0
__all__ = ['base_path', 'processed_data_dir', 'nifty500_csv']

# %% ../nbs/05_strategies.ipynb 3
import pandas as pd
import os
import nbdev
from .filters import *

# %% ../nbs/05_strategies.ipynb 4
base_path = nbdev.config.get_config().lib_path

# %% ../nbs/05_strategies.ipynb 5
processed_data_dir = base_path / "../Data/Bhavcopy/Processed/"
nifty500_csv = base_path / "../Data/Misc/ind_nifty500list.csv"
