# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_strategies.ipynb.

# %% auto 0
__all__ = ['base_path', 'processed_data_dir', 'nifty500_csv', 'get_nifty500', 'get_symbol_data', 'filter_stocks']

# %% ../nbs/05_strategies.ipynb 3
import pandas as pd
import os
import nbdev

# %% ../nbs/05_strategies.ipynb 4
base_path = nbdev.config.get_config().lib_path

# %% ../nbs/05_strategies.ipynb 5
processed_data_dir = base_path / "../Data/Bhavcopy/Processed/"
nifty500_csv = base_path / "../Data/Misc/ind_nifty500list.csv"

# %% ../nbs/05_strategies.ipynb 7
def get_nifty500():
    # Get Nifty500 list
    return pd.read_csv(nifty500_csv).Symbol.to_list()

# %% ../nbs/05_strategies.ipynb 8
def get_symbol_data(symbol):
    file_path = base_path / processed_data_dir / f"{symbol}.parquet"
    if file_path.exists():
        # print(f"File exists: {file_path}")
        return pd.read_parquet(file_path).assign(
            DATE=lambda x: x.DATE.dt.strftime("%d %b %Y")
        )
    else:
        # print(f"File does not exist: {file_path}")
        return None

# %% ../nbs/05_strategies.ipynb 9
def filter_stocks(symbols=None, strategy=None, days_lookback=2):
    if not symbols:
        symbols = get_nifty500()
    
    # for symbol in symbols:
    #     pass
    #     # df = get_symbol_data(symbol)
